# Generated by Django 3.0.6 on 2020-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='generator/images')),
                ('body', models.TextField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
    ]
